### ISSUE TITLE
Feature Request: File Name and Extension pre-fill, possible AI Export Menu Integration

### ISSUE THREAD

**Issue by wjramos** [choffmeister/adobe-illustrator-icnsexport#2]
This script is great, and I would like to contribute any way I can.

I've been using it for all of my contributions to [flat.icns](https://github.com/tinalatif/flat.icns), and there are a few features that would really help the workflow.

- Integration into the AI exporter menu (I don't know the limitations on this, or whether this is possible with a third-party script)
- Pre-population of the file name to match the AI file name and .icns file extension

**Comment by choffmeister** [comment]
Great to hear that the script is working for you :) As far as I remember integrating third party scripts anywhere else is not possible (this only works, when you go for full fledged plugin). Pre-populating the filename should be possible I guess.

Could you provide a PR for that?

**Comment by choffmeister** [comment]
I just found out, that you can add the script to the menu by putting it into the right location on your disk:

Windows: C:\Program Files\Adobe\Adobe lllustratorCC2014\Presets\[language]\Scripts\
Mac OS: /Applications/Adobe lllustrator CC 2014/Presets/[language]/Scripts/

I will add a comment on that to the README.

**Comment by choffmeister** [comment]
![illustrator-scripts](https://cloud.githubusercontent.com/assets/671620/7365169/e50125ce-ed8d-11e4-9a85-567cb4d3ea92.png)

**Comment by choffmeister** [comment]
I could not find any hint on how to preset the filename in the save dialog (see [here](http://jongware.mit.edu/iljscs6html/iljscs6/pc_File.html)).

**Comment by mknrls** [comment]
@choffmeister been looking around and i think some thing that could help you. 
At the same location where the script is located there's a SaveDocsAsSVG.jsx and SaveDocsAsPDFjsx (that almost have the same code) 

but the particular snippet that might interest you (hope that helps): 

```javascript 
/** Returns the file to save or export the document into.
	@param docName the name of the document
	@param ext the extension the file extension to be applied
	@param destFolder the output folder
	@return File object
*/
function getTargetFile(docName, ext, destFolder) {
	var newName = "";

	// if name has no dot (and hence no extension),
	// just append the extension
	if (docName.indexOf('.') < 0) {
		newName = docName + ext;
	} else {
		var dot = docName.lastIndexOf('.');
		newName += docName.substring(0, dot);
		newName += ext;
	}
	
	// Create the file object to save to
	var myFile = new File( destFolder + '/' + newName );
	
	// Preflight access rights
	if (myFile.open("w")) {
		myFile.close();
	}
	else {
		throw new Error('Access is denied');
	}
	return myFile;
}
```

**Comment by choffmeister** [comment]
Thanks. Do these scripts offer a save dialog? Or do they always save to {original-filename}.svg without showing a dialog?

**Comment by mknrls** [comment]
always save to {original-filename}.svg without showing a dialog witch is still a good option. The only dialog that is showed is to choose a location to save the file. check out the full jsx file get better idea like i posted just a snippet from it.

**Comment by choffmeister** [comment]
OK. Will look into it.

**Comment by choffmeister** [comment]
I consider this closed. If I am wrong feel free to reopen.
