### ISSUE TITLE
Request: Automatic naming and icns extention 

### ISSUE THREAD

**Issue by mknrls** [choffmeister/adobe-illustrator-icnsexport#3]
@choffmeister first off nice work :) I was wondering if was possible that automatically name your icons + icns extension without you writing it out. 

Ex: You have a ai file called adobe.ai, it would know that file is called adode so when you export it to an icon it would automatic called it adobe.icns

**Comment by choffmeister** [comment]
This relates to #2.

**Comment by choffmeister** [comment]
Closing this in favour of #2. Feel free to reopen if you think this is inappropriate.
